repos:
  # General hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # Python: black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^api/

  # Python: isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^api/

  # Python: flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^api/

  # Python: mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^api/

  # JavaScript/TypeScript: prettier (via local hook)
  # - repo: local
  #   hooks:
  #     - id: prettier
  #       name: prettier
  #       entry: npx prettier --write
  #       language: node
  #       types: [javascript, typescript, json, css, html, md]
  #       files: ^client/

  # # JavaScript/TypeScript: eslint (via local hook)
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: npx eslint .
  #       language: node
  #       types: [javascript, typescript]
  #       files: ^client/

  # - repo: https://github.com/prettier/prettier
  #   rev: "3.2.5"  # Use latest stable
  #   hooks:
  #     - id: prettier
  #       files: \.(js|jsx|ts|tsx|json|md|css|scss)$

  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: npx eslint .
  #       language: system
  #       types: [javascript, typescript]
  #       pass_filenames: false
  #       files: ^client/

  #     - id: tsc
  #       name: tsc
  #       entry: npx tsc --noEmit
  #       language: system
  #       types: [typescript]
  #       pass_filenames: false
  #       files: ^client/