services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: revent_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: revent_client
    ports:
      - "3000:3000"
    command: npm run start
    env_file:
      - .env
    depends_on:
      - api
