# Generated by Django 5.2.1 on 2025-05-31 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_calendar_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recurrence_date',
            new_name='recurrence_end_date',
        ),
    ]
