[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip = ["migrations"]

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
